version: '2'
services:
  vue:
    container_name: vue
    build: vue
    ports:
      - "8080:8080"
      - "80:8080"
    volumes:
      - "../vue:/app"
    network_mode: "bridge"

  flask:
    container_name: alaska-test
    volumes:
      - "../flask:/deploy"
    build: flask
    ports:
      - "5000:5000"

