version: '2'
services:
  vue:
    container_name: vue
    build: vue
    ports:
      - "8080:8080"
    volumes:
      - "../vue:/app"
    network_mode: "bridge"

  sails:
    container_name: sails
    ports:
      - "8090:1337"
    volumes:
      - "../sails/myapp:/server"
    build: sails

  flask:
    container_name: flask
    volumes:
      - "../flask:/deploy"
    build: flask
    ports:
      - "5000:5000"
  react:
    container_name: react
    volumes:
      - "../react/myapp:/app"
    build: react
    ports:
      - "8030:3000"

